### ISSUE TITLE
Logfilter Stopps working (Logfile is not continued)

### ISSUE THREAD

**Issue by Kweck** [laryakan/valheim-server-status#2]
Hi, it's me again.

I got another issue.
Now - as soon as I log out - the logging through the logfilter stops

I added a line to the launcher script get the raw logdata in a file to get the lines the logging stops.

Last line going through the logfilter is
04/07/2021 14:04:26: Destroying abandoned non persistent zdo -1265370345:815 owner -1265370345

The stdout itself continues with.
04/07/2021 14:04:26: Destroying abandoned non persistent zdo -1265370345:815 owner -1265370345
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04/07/2021 14:04:26: Disposing socket
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04/07/2021 14:04:26: Closing socket 76561197963567339
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04/07/2021 14:04:26:   send queue size:0
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04/07/2021 14:04:26: Disposing socket
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04/07/2021 14:04:26: Got status changed msg k_ESteamNetworkingConnectionState_ClosedByPeer
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04/07/2021 14:04:26: Socket closed by peer Steamworks.SteamNetConnectionStatusChangedCallback_t
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04/07/2021 14:04:26: Got status changed msg k_ESteamNetworkingConnectionState_None
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

**Comment by laryakan** [comment]
Hello,

Thanks again for your report 👍

The log output seems normal. You Can find logs in valheim-logs.d inside vss dir if you've kept default values (if needed).

How are you launching your valheim server ?

**Comment by Kweck** [comment]
I'm launching the server using your custom launcher. 

The logfile in the valheim-logs.d stops at the mentioned point suddenly after I log out from the server. 

What  i did was, I edited the launcher script to see what is coming from the server itself by adding the following:
**1> >( tee -a "$VALHEIMSERVERLOGDIR/meins.log" ) \**

`"$VHSERVERDIR/valheim_server.x86_64" \
-name "$VHSERVERNAME" \
-port $VHSERVERPORT \
-world "$VHSERVERWORLD" \
-password "$VHSERVERPASSWD" \
1> >( tee -a >("$VSSLOGFILTER") ) \
1> >( tee -a "$VALHEIMSERVERLOGDIR/meins.log" ) \
2> >( tee -a "$VALHEIMSERVERLOGDIR/`date +%Y-%m-%d`.stderr.log" >&2 )

`
So I get one additional logilfe "meins.log" showing the raw data coming from the server without parsing through the logfilter.
-rw-r--r--  1 steam steam   3849 Apr  7 13:52 2021-04-07.stderr.log
-rw-r--r--  1 steam steam  44115 Apr  7 14:04 2021-04-07.stdout.log
-rw-r--r--  1 steam steam 112071 Apr  8 09:28 meins.log


With that I can see the log data is still coming but after the mentioned line above the logfilter stops working and the 2021-04-07.stdout.log stops working after logging out but the meins.log keeps going. So the data is coming from the server but the logfilter stopped.
Ähm... you know what I mean? :D

You can see it on the timestamp also, 2021-04-07.stdout.log stopped yesterday at 14:04

Sorry for the clumsy explanation. Hope it get's a little bit clearer.

**Comment by laryakan** [comment]
Hey,

Did you set up valheim-server.service to launch the server with my custom launcher ? If so, once you logged out, what's service status ? Do you still have your valheim_server process running (you can see it using ps, pgrep or top) ?

**Comment by laryakan** [comment]
Also, you shouldn't redirect stdout 2 times :-)
You'd better added another `| tee -a "$VALHEIMSERVERLOGDIR/meins.log"`

**Comment by laryakan** [comment]
But it doesn't explain why the logfilter stopped...
Since it's when you log out, It probabbly has something to do with expression or grep I'm using inside it to catch a disconnection.

Does the offlineplayer file exists and the user executing the launcher has permissions to write inside it ?

You can also check if the logfilter is still running after you logged out.

![image](https://user-images.githubusercontent.com/6781104/114087464-37a49400-98b4-11eb-8a94-03363b51bb2e.png)

or `pgrep  vss.log-filter` should return the logfilter pid.

**Comment by laryakan** [comment]
okay, I just figured out that Irongate has changed their log format...

**Comment by laryakan** [comment]
hu... I just checked my self, but I don't have `-` before zdo and owner.
`04/07/2021 14:04:26: Destroying abandoned non persistent zdo -1265370345:815 owner -1265370345`
more like
`04/07/2021 14:04:26: Destroying abandoned non persistent zdo 1265370345:815 owner 1265370345`
I also get things in stdout logfile after logging out. It's weird. I checked my server and it's up to date.

**Comment by laryakan** [comment]
the `-` shouldn't be a problem anyway, if you also got it when you connect.

**Comment by Kweck** [comment]
I will have a look at it tomorrow. Today we had to prepare for the dragon queen ;)

>>nevermind, I couldn't sleep without taking care about it :D

**Comment by Kweck** [comment]
Yes, I do use the launcher and the service is still running after logging out.
Also the vss.log-filter is running 
_CGroup: /system.slice/valheim-server.service
             ├─1731247 /bin/bash /home/steam/valheim-server-status/launcher/start_server_custom.sh
             ├─1731288 /home/steam/Valheim/valheim_server.x86_64 -name Grutschmork -port 2456 -world Dedicated -password password
             ├─1731289 /bin/bash /home/steam/valheim-server-status/launcher/start_server_custom.sh
             ├─1731290 /bin/bash /home/steam/valheim-server-status/launcher/start_server_custom.sh
             ├─1731291 /bin/bash /home/steam/valheim-server-status/launcher/start_server_custom.sh
             ├─1731294 /bin/bash /home/steam/valheim-server-status/launcher/start_server_custom.sh
             ├─1731295 tee -a /dev/fd/63
             ├─1731296 /bin/bash /home/steam/valheim-server-status/**vss.log-filter**
             ├─1731297 tee -a /home/steam/valheim-server-status/valheim-logs.d/2021-04-08.stderr.log
             └─1736110 grep -393533849 /home/steam/valheim-server-status/data/online-players_

I get the minus also when connecting but I've just seen that after login i get in the status the following "too many arguments"


_Apr 08 22:57:06 server1 start_server_custom.sh[1731295]: (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
Apr 08 22:57:08 server1 start_server_custom.sh[1734862]: /home/steam/valheim-server-status/discord/update: line 11: [: **too many arguments**_


the offline player and online player files are existing and they are writable for the user also. 

Hmm...  I'm not sure about it, but if I remember right everything works fine when the other player connects and disconnects - and he has no "-" before zdo/owner...
But I have to verify that.

**Comment by laryakan** [comment]
I'll check that this evening :-) or at least this weekend.
It seems obvious indeed 
`└─1736110 grep -393533849 /home/steam/valheim-server-status/data/online-players`
lol

**Comment by laryakan** [comment]
Thx again for your feedback @Kweck  :-)

I've made a bugfix to prevent the logfilter to crash when a player with zoid starting with a minus is loggin out :-) It's fixed on the `main` branch and in tag `2.1.1`

**Comment by laryakan** [comment]
can you confirm it's fixed please ? :-)

_pull main branch or checkout the tag, then restart your services_

**Comment by Kweck** [comment]
I will do so. Obviously the zoid is changing. Today I had a positive number.
I will have an eye on it and get back to you as soon as I have a negative ID.

**Comment by laryakan** [comment]
@Kweck any news about this issue ? :-)

**Comment by Kweck** [comment]
I didn't had a negative ID until then but keeping an eye on it.

Edit:
Ok...  that said and just logged in to test it again I got one and it works fine. Seems to be solved.

**Comment by laryakan** [comment]
Nice !
